version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:16.2
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - db
