"""add water_consumption table

Revision ID: 47ec2650237f
Revises: 5ae0b0c5e4d3
Create Date: 2024-02-20 17:14:28.052623

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47ec2650237f"
down_revision: Union[str, None] = "5ae0b0c5e4d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "water_consumption",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cup_size_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cup_size_id"],
            ["cup_size.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("water_consumption")
    # ### end Alembic commands ###
