"""add cup_size table

Revision ID: 5ae0b0c5e4d3
Revises: 9e31f54d13d1
Create Date: 2024-02-19 21:13:48.986929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae0b0c5e4d3'
down_revision: Union[str, None] = '9e31f54d13d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cup_size',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.Column('amount_ml', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_table('cup_size')
    # ### end Alembic commands ###
