"""update names of relationships in the water_consumption table

Revision ID: 7308aa43777b
Revises: f8f86ca56b74
Create Date: 2024-02-20 18:10:42.522194

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "7308aa43777b"
down_revision: Union[str, None] = "f8f86ca56b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
