"""update names of relationships in the water_consumption table (2)

Revision ID: aa29620e7b8e
Revises: 7308aa43777b
Create Date: 2024-02-20 19:05:11.615573

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "aa29620e7b8e"
down_revision: Union[str, None] = "7308aa43777b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
